name: Selenium Uptime Bot

on:
  workflow_dispatch:     # Manual trigger
  schedule:
    - cron: '* * * * *'  # Every 1 minute

jobs:
  run-selenium-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        # Only link chromedriver if it doesn't exist (avoid errors)
        if [ ! -f /usr/bin/chromedriver ]; then
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        fi

    - name: Run your Selenium bot (main.py)
      env:
        PATH: /usr/lib/chromium-browser:$PATH
      run: python main.py
