name: Webpage Keep-Alive Bot

on:
  schedule:
    - cron: '*/65 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    - name: Run Bot
      env:
        PATH: /usr/lib/chromium-browser/:$PATH
      run: |
        python main.py
