name: Webpage Keep-Alive Bot

on:
  workflow_dispatch:        # Manual run
  schedule:
    - cron: '* * * * *'     # Every 1 minute

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chromium and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run main.py
      env:
        PATH: /usr/lib/chromium-browser/:$PATH
      run: |
        python main.py
