name: Run Bot

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
    
    - name: Run bot
      run: |
        export PATH=$PATH:/usr/lib/chromium-browser/
        python bot.py
